version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: . 
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers=9 --threads=9
    volumes:
      - static_volume:/usr/src/app/static
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=dataground
      - DB_USER=wi
      - DB_PASSWORD=password
volumes:
  static_volume: