version: '3'

services:
  nginx:
    build: ./nginx
    volumes:
      - ./static:/usr/src/app/static
    ports:
      - 80:80
    depends_on:
      - web
  web:
    build: . 
    command: bash -c "
            python3 manage.py collectstatic --no-input &&
            gunicorn config.wsgi:application -b 0:8000"

    volumes:
      - ./static:/usr/src/app/static
      - ./:/usr/src/app/
    # ports:
    #   - 8000:8000
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
      - DB_NAME=dataground
      - DB_USER=wi
      - DB_PASSWORD=password
volumes:
  static: