# Generated by Django 3.2.19 on 2023-06-29 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.CharField(max_length=100)),
                ('player_name', models.CharField(max_length=100)),
                ('shardid', models.CharField(max_length=100)),
                ('matchId', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='weapon_parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts_name', models.CharField(max_length=100)),
                ('parts_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_name', models.CharField(max_length=100)),
                ('weapon_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='weapon_mastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Weapon_name', models.CharField(max_length=100)),
                ('Item_Weapon_classification', models.CharField(max_length=50)),
                ('Item_Weapon_XPtotal', models.IntegerField()),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.players', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='match_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamemode', models.CharField(max_length=20)),
                ('mapname', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('match_type', models.CharField(max_length=20)),
                ('asset_url', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField()),
                ('matchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.players', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='match_participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('accountId', models.CharField(max_length=200)),
                ('rosterId', models.CharField(max_length=200)),
                ('team_ranking', models.IntegerField()),
                ('dbnos', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('damage_dealt', models.FloatField()),
                ('headshot_kills', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('longestkill', models.IntegerField()),
                ('team_kills', models.IntegerField()),
                ('ride_distance', models.FloatField()),
                ('swim_distance', models.FloatField()),
                ('walk_distance', models.FloatField()),
                ('matchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.players')),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchId', models.CharField(max_length=200)),
                ('player_name', models.CharField(max_length=100)),
                ('accountId', models.CharField(max_length=200)),
                ('team_id', models.IntegerField()),
                ('victim', models.CharField(max_length=100)),
                ('killer', models.CharField(max_length=100)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('location_z', models.FloatField()),
                ('_D', models.DateTimeField()),
                ('asset_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.match_summary')),
            ],
        ),
    ]
