# Generated by Django 3.2.19 on 2023-06-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='players',
            unique_together={('accountId', 'matchId')},
        ),
    ]
