# Generated by Django 3.2.19 on 2023-07-03 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20230629_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_summary',
            name='matchId',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='matchId',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='services.match_summary'),
        ),
        migrations.AlterUniqueTogether(
            name='match_participant',
            unique_together={('accountId', 'matchId')},
        ),
    ]
