# Generated by Django 3.2.19 on 2023-07-04 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20230704_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon_mastery',
            name='Item_Weapon_classification',
        ),
        migrations.AlterField(
            model_name='match_participant',
            name='matchId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.match_summary'),
        ),
        migrations.AlterField(
            model_name='match_summary',
            name='matchId',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='weapon_mastery',
            name='accountId',
            field=models.CharField(max_length=100),
        ),
    ]
