# Generated by Django 3.2.19 on 2023-07-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20230704_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_participant',
            name='matchId',
            field=models.CharField(max_length=200),
        ),
    ]
